### ISSUE TITLE
Cannot run the website

### ISSUE THREAD

**Issue by milochen0418** [LineIndent/pyneweb#1]
Clean all built files by the following to ensure no cached file influent the testing. 
```bash
rm -rf .web
for i in $(find ./ | grep __pycache__$); do rm -rf $i; done
```
Python version : Python 3.10.11
```bash
pyneweb-init
pc init
pc run 
```

Then we can see the following error.
```
    from routes import *
ModuleNotFoundError: No module named 'routes'
```

When I test it, the following is the latest commit
- https://github.com/LineIndent/pyneweb/commit/c5abefe71e44128941ddad89aff8a7b6b6eb6a8e

When I meet this issue, I also try to do 

```
pip install routes
```

Then the code can be run, but there is some issue like the following.

Should I need to do  this step  pip install routes? 

<img width="1436" alt="Screenshot 2023-05-11 at 10 52 15 AM" src="https://github.com/LineIndent/pyneweb/assets/12568287/558a9c7f-d1dd-4eb9-bafa-e22f3994454d">

**Comment by milochen0418** [comment]
I use wrong way to init the project.

**Comment by milochen0418** [comment]
After use `pyneweb-init`

It's still have the same issue.

**Comment by LineIndent** [comment]
I see the issue - it's a ordering problem and the video demo I sent didn't cover it. 

What you do is first install the libraries, both pyneweb and pynecone. 

Then run the pyneweb-init command. 

Then inside your main pynecone file, after app.compile() set the script(app) method. Make sure to import it via from logic.script import script. 

After the above import, also import from logic.states import State

Then run the pc run command. 

This should generate a routes folder with the corresponding files to the YAML file. If this is generated, you then set from routes import *

I should probably work on reducing the steps, since it may be a little tedious. 

Let me know if this worked

**Comment by milochen0418** [comment]
> mpile() set the script(app) method. Make sure to import it via from logic.script import script.
> 
> After the above import, also import from logic.states import State
> 
> Then run the pc run command.
> 
> This should generate a routes folder with the corresponding files to the YAML file. If this is generated, you then set from routes import *

I don't understand your step. 
All I do is follow your step. 

You should clean all __pycache__ and .web first to make sure your environment is clean. 
I create virtual environment, and cannot use yours by your steps.

**Comment by milochen0418** [comment]
@LineIndent  
Can you create your virtual Python environment ( clean environment.) 
Try to do every command and note them. 
Because the only thing I can do is follow yours. 

(1)
First, you must clean all __pycache__ and .web. 
Don't keep this built-byte code. If you keep them, the user cannot run the execution build from the source code. 
So, delete them first. 

(2) 
Create a Python virtual environment. In my case, I use the anaconda. 
You should make your project can be run from this environment. and note every step of what you did. 
When you do this work, other people can follow your steps to do the same thing. 

For example, in your README.md, you only write one thing `pyneweb-init`

So, nobody can guess what you mean. 
Because when they do this, they cannot see anything. 

Ensure everyone who comes here can build and run your source code well. 
It's better to help more people to touch your exciting project.

**Comment by LineIndent** [comment]
I'll definitely update the README file to better explain. 

I replicated the installation process in a clean directory with a clean environment. I sent a video of the steps in the Discord channel. 

Let me know if it works now.

**Comment by milochen0418** [comment]
> ate the README file to better explain.

Thank you very much:D  Glad to have an opportunity to run your project ^_^

**Comment by LineIndent** [comment]
@milochen0418 I re worked the CLI commands and now it works as expected. 

You can update the pyneweb library and simply run ```pyneweb-init``` and this will create all the files and folders. It will also setup the ``` pc init ``` command for you and change the code inside the main file. 

I'll close this issue for now, and please let me know if it worked. Thanks again!
